"""Three live synthetic event chains; at most seven real notification events.

Existing accounts only. AI risk is generated by the existing prediction model,
not inserted as an invented probability. Records stay private in this run.
"""
import argparse
import base64
import hashlib
import hmac
import json
import subprocess
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4


def main(args):
    args.output.mkdir(parents=True,exist_ok=True)
    if (args.output/'state.json').exists():raise FileExistsError('use a new event run')
    private=dict(line.split('=',1) for line in (args.project/'.env').read_text().splitlines() if '=' in line and not line.startswith('#'))
    def sql(query):return subprocess.check_output(['docker','exec','powersystem-stage4-postgres-1','psql','-U','powersystem','-d','powersystem','-Atqc',query],text=True).strip()
    user=int(sql("SELECT id FROM users WHERE role='admin' ORDER BY id LIMIT 1").splitlines()[0])
    encode=lambda value:base64.urlsafe_b64encode(json.dumps(value).encode()).decode().rstrip('=')
    raw=encode({'alg':'HS256','typ':'JWT'})+'.'+encode({'sub':str(user),'exp':int(time.time())+3600})
    jwt=raw+'.'+base64.urlsafe_b64encode(hmac.new(private['JWT_SECRET'].encode(),raw.encode(),hashlib.sha256).digest()).decode().rstrip('=')
    opener=urllib.request.build_opener(urllib.request.ProxyHandler({}))
    def api(method,path,body=None):
        req=urllib.request.Request(args.url+path,method=method,data=json.dumps(body).encode() if body is not None else None,
            headers={'Content-Type':'application/json','Authorization':'Bearer '+jwt})
        with opener.open(req,timeout=50) as result:return json.load(result)['data']
    cases=[];state={'run_id':uuid4().hex[:8],'devices':[],'rules':[],'alarm_ids':[],'monitor_key':None,'notification_budget':7}
    if args.resume_state:
        original=args.resume_state.read_bytes();state=json.loads(original)
        if state.get('monitor_key') is not None or len(state['devices'])!=2 or len(state['alarm_ids'])!=2:raise ValueError('resume only before monitor acceptance')
        expected=['INV-V2M4-'+state['run_id']+'-'+suffix for suffix in ('temperature','ai')]
        if [d['code'] for d in state['devices']]!=expected:raise ValueError('unowned event assets')
        for d in state['devices']:
            if sql('SELECT device_code FROM devices WHERE id='+str(d['id']))!=d['code']:raise ValueError('event ownership mismatch')
            sql('UPDATE devices SET deleted_at=NULL WHERE id='+str(d['id']))
        for identifier in state['alarm_ids']:
            if int(sql('SELECT device_id FROM alarm_records WHERE id='+str(identifier))) not in [d['id'] for d in state['devices']]:raise ValueError('alarm ownership mismatch')
            sql("UPDATE alarm_records SET recovered_at=NULL,status='unhandled' WHERE id="+str(identifier))
        for identifier in state['rules']:sql('UPDATE alarm_rules SET enabled=true WHERE id='+str(identifier))
        state['resume_source_sha256']=hashlib.sha256(original).hexdigest()
    def save(): (args.output/'state.json').write_text(json.dumps(state,indent=2))
    def check(name,passed,detail=None):
        cases.append({'case':name,'passed':bool(passed),'detail':detail})
        (args.output/'cases.json').write_text(json.dumps(cases,ensure_ascii=False,indent=2))
        if not passed:raise AssertionError(name)
    def wait(label,read,timeout=360,refresh=None):
        until=time.monotonic()+timeout
        refreshed=time.monotonic()
        while time.monotonic()<until:
            value=read()
            if value:return value
            if refresh and time.monotonic()-refreshed>=60:
                refresh();refreshed=time.monotonic()
            time.sleep(2)
        raise TimeoutError(label)
    def inside(container,code,payload):
        result=subprocess.run(['docker','exec','-i','powersystem-stage4-'+container+'-1','python','-c',code],input=json.dumps(payload),text=True,capture_output=True)
        if result.returncode:raise RuntimeError('internal '+container+' command failed')
        return json.loads(result.stdout)
    publish_code="import json,sys;from paho.mqtt.publish import multiple;p=json.load(sys.stdin);multiple([{'topic':'device/telemetry','payload':json.dumps(x),'qos':1} for x in p],hostname='emqx');print(json.dumps({'published':len(p)}))"
    save()
    try:
        for suffix in (() if args.resume_state else ('temperature','ai')):
            code='INV-V2M4-'+state['run_id']+'-'+suffix
            d=api('POST','/api/v1/devices',{'device_code':code,'name':'V2-M4 synthetic '+suffix+' test','dev_type':'inverter','vendor':'synthetic','station_code':'ST-V2M4','group_name':'v2m4-'+state['run_id']})
            state['devices'].append({'id':d['id'],'code':code});save()
        device,ai=state['devices']
        if not args.resume_state:
            rule=api('POST','/api/v1/alarm-rules',{'device_id':device['id'],'metric':'temperature','operator':'>','threshold':60,'level':'major','enabled':True})
            state['rules'].append(rule['id']);save()
        def sample(seq,temp):return {'schema_version':1,'run_id':'v2m4-'+state['run_id'],'device_id':device['code'],'station_id':'ST-V2M4','seq':seq,'ts_ms':int(time.time()*1000),'voltage':400,'current':10,'temperature':temp,'power':6.86,'status':1,'fault_code':0}
        if args.resume_state:
            alarm=state['alarm_ids'][0]
            prior=json.loads((args.resume_state.parent/'cases.json').read_text())
            check('original MQTT under 10 seconds evidence retained',any(x['case']=='MQTT original alarm under 10 seconds' and x['passed'] for x in prior))
        else:
            started=time.monotonic();inside('simulator',publish_code,[sample(0,70)])
            alarm=int(wait('temperature alarm',lambda:sql("SELECT id FROM alarm_records WHERE device_id="+str(device['id'])+" AND metric='temperature' ORDER BY id DESC LIMIT 1"),10))
            state['alarm_ids'].append(alarm);save();check('MQTT original alarm under 10 seconds',time.monotonic()-started<=10)
        # Build precursor and recovery windows with the same synthetic generator
        # used by the first-version prediction replay. Probe before publishing.
        ai_code=r"""import json,sys,time,math,urllib.request
from paho.mqtt.publish import multiple
p=json.load(sys.stdin);end=int(time.time()//60)*60000+1000;onset=end+p['lead']*60000;points=[]
for seq in range(30):
 ts=end-(29-seq)*60000;hour=12+(ts-onset)/3600000;sun=max(0,math.sin(math.pi*(hour-6)/12));power=100*sun**1.6*.95;voltage=400+.5*math.sin(seq/7);lead=(onset-ts)/60000;ramp=12*(1-lead/60) if 0<lead<=60 else 0;temperature=25+.25*power+3*max(0,math.sin(math.pi*(hour-7)/12))+ramp
 points.append({'schema_version':1,'run_id':p['run']+'-'+str(end),'device_id':p['code'],'station_id':'ST-V2M4','seq':seq,'ts_ms':ts,'voltage':round(voltage,3),'current':round(power*1000/(math.sqrt(3)*voltage*.99),3),'temperature':round(temperature,3),'power':round(power,3),'status':1,'fault_code':0})
body={'device_id':p['id'],'window_end_ms':end,'samples':points}
req=urllib.request.Request('http://ai-predict:8090/predict',data=json.dumps(body).encode(),headers={'Content-Type':'application/json'})
with urllib.request.urlopen(req,timeout=10) as r:prediction=json.load(r)
assert prediction['risk_level']==p['expected']
multiple([{'topic':'device/telemetry','payload':json.dumps(x),'qos':1} for x in points],hostname='emqx')
print(json.dumps({'window_end_ms':end,'prediction':prediction,'published':30}))"""
        high=json.loads((args.resume_state.parent/'ai-high.json').read_text()) if args.resume_state else inside('simulator',ai_code,{'id':ai['id'],'code':ai['code'],'run':'v2m4-ai-'+state['run_id'],'lead':3,'expected':'high'})
        (args.output/'ai-high.json').write_text(json.dumps(high,indent=2))
        high_payload={'id':ai['id'],'code':ai['code'],'run':'v2m4-ai-'+state['run_id'],'lead':3,'expected':'high'}
        ai_alarm=int(wait('real AI risk alarm',lambda:sql("SELECT id FROM alarm_records WHERE device_id="+str(ai['id'])+" AND metric='ai_failure_risk' AND recovered_at IS NULL ORDER BY id DESC LIMIT 1"),refresh=lambda:inside('simulator',ai_code,high_payload)))
        if not args.resume_state:state['alarm_ids'].append(ai_alarm)
        save();check('real prediction model creates AI alarm',True)
        starts=datetime.now(timezone.utc).isoformat();fingerprint='v2m4-'+state['run_id']
        batch={'version':'4','groupKey':'v2m4-'+state['run_id'],'status':'firing','receiver':'agent','groupLabels':{},'commonLabels':{},'commonAnnotations':{},'alerts':[{'status':'firing','labels':{'alertname':'PowerSystemAPIDown','severity':'critical','test_run':state['run_id']},'annotations':{'summary':'V2-M4 合成监控通知测试 '+state['run_id']},'startsAt':starts,'endsAt':'0001-01-01T00:00:00Z','fingerprint':fingerprint}]}
        monitor_code="import sys,json,urllib.request;from agent.config import Config;c=Config.load();p=json.load(sys.stdin);r=urllib.request.Request('http://127.0.0.1:8092/internal/agent/monitor-events',data=json.dumps(p).encode(),headers={'Authorization':'Bearer '+c.monitor_token,'Content-Type':'application/json'});print(json.dumps({'http':urllib.request.urlopen(r,timeout=10).status}))"
        check('monitor accepted',inside('agent',monitor_code,batch)['http']==200)
        state['monitor_key']='monitor:'+fingerprint+':'+datetime.fromisoformat(starts).strftime('%Y-%m-%dT%H:%M:%S.%f').rstrip('0')+'Z';save()
        def monitor_notify(payload):
            code="import sys,json,urllib.request;p=json.load(sys.stdin);r=urllib.request.Request('http://feishu-adapter:8091/alertmanager',data=json.dumps(p).encode(),headers={'Content-Type':'application/json'});print(json.dumps({'http':urllib.request.urlopen(r,timeout=12).status}))"
            check('real monitor notification '+payload['status'],inside('simulator',code,payload)['http']==200)
        monitor_notify(batch)
        keys=['alarm:'+str(x) for x in state['alarm_ids']]+[state['monitor_key']]
        def interpretations():
            raw=sql("SELECT json_agg(json_build_object('id',id,'event_key',event_key,'category',category,'task_status',task_status,'occurred_at',occurred_at,'updated_at',updated_at,'evidence',evidence,'result',result)) FROM agent_interpretations WHERE event_key IN ("+','.join("'"+k+"'" for k in keys)+")")
            rows=json.loads(raw) if raw and raw!='null' else []
            return rows if len(rows)==3 and all(x['task_status'] in ('completed','degraded') for x in rows) else None
        rows=wait('three interpretations',interpretations,180)
        (args.output/'interpretations.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
        for row in rows:check('real server answered '+row['category'],row['result']['status']=='answered')
        api('POST','/api/v1/alarms/'+str(alarm)+'/ack',{})
        inside('simulator',publish_code,[sample(1,30)])
        wait('temperature recovered',lambda:sql('SELECT recovered_at IS NOT NULL FROM alarm_records WHERE id='+str(alarm))=='t',30)
        # The model uses unique minute windows. Recovery must have a new end.
        high_end=int(sql('SELECT max(window_end_ms) FROM prediction_records WHERE device_id='+str(ai['id'])))
        while int(time.time()//60)*60000+1000<=high_end:time.sleep(2)
        low_payload={'id':ai['id'],'code':ai['code'],'run':'v2m4-ai-low-'+state['run_id'],'lead':120,'expected':'low'}
        low=inside('simulator',ai_code,low_payload)
        (args.output/'ai-low.json').write_text(json.dumps(low,indent=2))
        wait('AI recovered',lambda:sql('SELECT recovered_at IS NOT NULL FROM alarm_records WHERE id='+str(ai_alarm))=='t',refresh=lambda:inside('simulator',ai_code,low_payload))
        batch['status']='resolved';batch['alerts'][0].update(status='resolved',endsAt=datetime.now(timezone.utc).isoformat())
        check('monitor recovered accepted',inside('agent',monitor_code,batch)['http']==200);monitor_notify(batch)
        def notifications():
            raw=sql('SELECT json_agg(json_build_object(\'event_key\',event_key,\'sent\',sent_at IS NOT NULL,\'attempts\',attempts)) FROM business_notification_outbox WHERE event_key IN ('+','.join("'alarm:"+str(identifier)+':'+suffix+"'" for identifier,suffix in ((alarm,'triggered'),(alarm,'acknowledged'),(alarm,'recovered'),(ai_alarm,'triggered'),(ai_alarm,'recovered')))+')')
            rows=json.loads(raw) if raw and raw!='null' else []
            return rows if len(rows)==5 and all(row['sent'] for row in rows) else None
        notices=wait('five business notifications accepted',notifications,180)
        check('five business notifications',len(notices)==5)
        (args.output/'notifications.json').write_text(json.dumps({'business':notices,'monitor_HTTP200':2,'maximum_events':7,'group_visibility':'not_verified'},indent=2))
        (args.output/'summary.json').write_text(json.dumps({'completed':True,'passed':True,'cases':cases,'notification_events':7,'group_visibility':'not_verified'},ensure_ascii=False,indent=2))
        print(json.dumps({'passed':True,'checks':len(cases),'notification_events':7}))
    finally:
        for identifier in state['rules']:
            sql('UPDATE alarm_rules SET enabled=false WHERE id='+str(identifier))
        for device in state['devices']:
            # On interruption retire only this run's synthetic alarms, without
            # generating additional notification events beyond the budget.
            sql("UPDATE alarm_records SET recovered_at=now(),status='recovered' WHERE recovered_at IS NULL AND device_id="+str(device['id']))
            sql('UPDATE devices SET deleted_at=now() WHERE id='+str(device['id']))
        save()


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--project',type=Path,default=Path('/opt/powersystem'));parser.add_argument('--url',required=True);parser.add_argument('--output',type=Path,required=True);parser.add_argument('--resume-state',type=Path)
    args=parser.parse_args();args.url=args.url.rstrip('/');main(args)
