apiVersion: 1
datasources:
  - name: PowerSystem Prometheus
    uid: powersystem-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
